/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-06-25 05:02:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.add;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class address_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>주소록</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[주소록]</h1>\r\n");
      out.write("\t<table border=1>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Name : </td>\r\n");
      out.write("\t\t\t<td width=400><input type=\"text\" id=\"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Address : </td>\r\n");
      out.write("\t\t\t<td width=400><input type=\"text\" id=\"address\" size=53></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=100>Telephone : </td>\r\n");
      out.write("\t\t\t<td width=400><input type=\"text\" id=\"tel\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"button\" value=\"입력\" id=\"btnInsert\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<table id=\"tbl\" border=1></table>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=50>No.</th>\r\n");
      out.write("\t\t<th width=100>Name</th>\r\n");
      out.write("\t\t<th width=300>Address</th>\r\n");
      out.write("\t\t<th width=100>Telephone</th>\r\n");
      out.write("\t\t<th>수정/삭제</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t{{#each list}}\r\n");
      out.write("\t\t<tr class=\"row\">\r\n");
      out.write("\t\t\t<td class=\"id\">{{id}}</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" value=\"{{name}}\" size=15 class=\"name\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" value=\"{{address}}\" size=40 class=\"address\"></td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" value=\"{{tel}}\" size=15 class=\"tel\"></td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<button class=\"btnUpdate\">수정</button>\r\n");
      out.write("\t\t\t\t<button class=\"btnDelete\">삭제</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tgetList();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/add/rest/list\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(!confirm(\"저장하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar name=$(\"#name\").val();\r\n");
      out.write("\t\tvar address=$(\"#address\").val();\r\n");
      out.write("\t\tvar tel=$(\"#tel\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/add/rest/insert\",\r\n");
      out.write("\t\t\tdata:{\"name\":name, \"address\":address, \"tel\":tel},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"등록되었습니다.\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .btnUpdate\", function(){\r\n");
      out.write("\t\tif(!confirm(\"수정하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar id=row.find(\".id\").html();\r\n");
      out.write("\t\tvar name=row.find(\".name\").val();\r\n");
      out.write("\t\tvar address=row.find(\".address\").val();\r\n");
      out.write("\t\tvar tel=row.find(\".tel\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/add/rest/update\",\r\n");
      out.write("\t\t\tdata:{\"id\":id, \"name\":name, \"address\":address, \"tel\":tel},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"수정되었습니다.\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .btnDelete\", function(){\r\n");
      out.write("\t\tif(!confirm(\"삭제하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\tvar id=row.find(\".id\").html();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/add/rest/delete\",\r\n");
      out.write("\t\t\tdata:{\"id\":id},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
