/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-09 06:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>회원가입</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("    \ta {text-decoration:none;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<h1>[회원가입]</h1>\r\n");
      out.write("    <form name=\"frm\" action=\"insert\" method=\"post\">\r\n");
      out.write("        <table border=1 width=400>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td width=150>회원 아이디</td>\r\n");
      out.write("               <td>\r\n");
      out.write("\t               <input type=\"text\" name=\"id\" size=15>\r\n");
      out.write("\t               <a href=\"#\" id=\"btnCheck\">[중복확인]</a>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td width=150>회원 비밀번호</td>\r\n");
      out.write("                <td><input type=\"password\" name=\"pass\" size=20></td> </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td width=150>회원 성명</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"name\" size=20></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <input type=\"submit\" value=\"가입\">\r\n");
      out.write("        <input type=\"reset\" value=\"취소\">\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tvar check=false;\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm).submit(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tif(!check) {\r\n");
      out.write("\t\t\talert(\"아이디를 중복체크 하세요.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif($(frm.pass).val()==\"\" || $(frm.name).val()==\"\") {\r\n");
      out.write("\t\t\t\talert(\"비밀번호와 이름을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(frm.id).change(function(){\r\n");
      out.write("\t\tcheck=false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#btnCheck\").on(\"click\", function(e){\r\n");
      out.write("\t\tvar id=$(frm.id).val();\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/user/login\",\r\n");
      out.write("\t\t\tdata:{\"id\":id},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data!=0) {\r\n");
      out.write("\t\t\t\t\talert(\"이미존재하는 아이디 입니다.\");\r\n");
      out.write("\t\t\t\t\t$(frm.id).focus();\r\n");
      out.write("\t\t\t\t} else if($(frm.id).val()==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t$(frm.id).focus();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"사용 가능한 아이디 입니다.\");\r\n");
      out.write("\t\t\t\t\tcheck=true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
