/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-10 04:11:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class receive_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592786290475L));
    _jspx_dependants.put("jar:file:/C:/data/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex19/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/data/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex19/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>받은 메세지</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<h1>[받은 메세지]</h1>\r\n");
      out.write("\t<div style=\"margin-bottom:10px;\"> \r\n");
      out.write("\t\t<table border=1>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=280>받은이 : <span id=name>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t<td width=280>포인트:<span id=\"point\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>점</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<button onClick=\"location.href='list'\">목록</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id=\"tbl\" border=1></table>    \r\n");
      out.write("\t  <script id=\"temp\" type=\"text/x-handlebars-template\"> \r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>NO.</th>\r\n");
      out.write("\t\t\t\t\t<th>Sender</th>\r\n");
      out.write("\t\t\t\t\t<th>Message</th>\r\n");
      out.write("\t\t\t\t\t<th>View</th>\r\n");
      out.write("\t\t\t\t\t<th>삭제</th>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t{{#each .}}\r\n");
      out.write("\t\t\t\t<tr class=\"row\" {{printStyle readDate}}>\r\n");
      out.write("\t\t\t\t\t<td class=\"mid\">{{mid}}</td>\r\n");
      out.write("\t\t\t\t\t<td width=150>{{sender}}:{{name}}</td>\r\n");
      out.write("\t\t\t\t\t<td width=325>{{message}}</td>\r\n");
      out.write("\t\t\t\t\t<td><button class=\"view\">view</button></td>\r\n");
      out.write("\t\t\t\t\t<td><button class=\"del\">delete</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t{{/each}}\r\n");
      out.write("\t  </script>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div style=\"background:gray; color:white; margin:10px 0px 10px 0px; padding:10px;width:500px; border-radius:10px;\" id=\"divMessage\">\r\n");
      out.write("\t  \tSender : <span id=\"sender\"></span><br>\r\n");
      out.write("\t  \tMessage : <span id=\"message\"></span><br>\r\n");
      out.write("\t  \tSend Date : <span id=\"sendDate\"></span><br>\r\n");
      out.write("\t  \tRead Date : <span id=\"readDate\"></span>\r\n");
      out.write("\t  </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tvar name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tvar point=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t$(\"#name\").html(name);\r\n");
      out.write("\t$(\"#point\").html(point);\r\n");
      out.write("\t\r\n");
      out.write("\t   Handlebars.registerHelper(\"printStyle\", function(readDate){\r\n");
      out.write("\t\t      var src;\r\n");
      out.write("\t\t      if(readDate==null) src=\"style=color:red\";\r\n");
      out.write("\t\t      return src\r\n");
      out.write("\t\t   })\r\n");
      out.write("\t\r\n");
      out.write("getList();\r\n");
      out.write("\t$(\"#divMessage\").hide();\r\n");
      out.write("\tfunction getList() {\r\n");
      out.write("\t\tvar id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"get\",\r\n");
      out.write("\t\turl : \"/list/receive\",\r\n");
      out.write("\t\tdata:{\"id\":id},\r\n");
      out.write("\t\tdataType : \"json\",\r\n");
      out.write("\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t$(\"#tbl\").html(temp(data));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .view\", function(){\r\n");
      out.write("\t\tvar mid=$(this).parent().parent().find(\".mid\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/message/read\",\r\n");
      out.write("\t\t\tdata:{\"mid\":mid},\r\n");
      out.write("\t\t\tdataType:\"json\", //리턴타입이 있을때 줌, 데이터를 받아올때 적는거임\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t$(\"#sender\").html(data.sender+ \" - \" + data.name);\r\n");
      out.write("\t\t\t\t$(\"#message\").html(data.message);\r\n");
      out.write("\t\t\t\t$(\"#sendDate\").html(data.sendDate);\r\n");
      out.write("\t\t\t\t$(\"#readDate\").html(data.readDate);\r\n");
      out.write("\t\t\t\t$(\"#divMessage\").show();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\t\turl:\"/user/getUser\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:{\"id\":id},\r\n");
      out.write("\t\t\t\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#point\").html(data.point);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".row .del\", function(){\r\n");
      out.write("\t\tif(!confirm(\"삭제하시겠습니까?\")) return;\r\n");
      out.write("\t\tvar mid=$(this).parent().parent().find(\".mid\").html();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/message/rdelete\",\r\n");
      out.write("\t\t\tdata:{\"mid\":mid},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
