/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-09 01:20:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/data/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex17/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592786290475L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>댓글목록</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.divContent{width:500px;padding:10px;margin-bottom:10px;\r\n");
      out.write("\t\t\tbackground:gray;color:white;border:1px solid black;\r\n");
      out.write("\t\t\tfont-size:10px;}\r\n");
      out.write("\t\t#divInput{width:500px;padding:10px;margin-bottom:10px;\r\n");
      out.write("\t\t\tbackground:gray;color:white;font-size:10px;}\t\r\n");
      out.write("\t\tbutton{font-size:10px;}\r\n");
      out.write("\t\ta{text-decoration:none;}\r\n");
      out.write("\t\t.active{color:red;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divInput\">\r\n");
      out.write("\t\t게시글수:<span id=\"count\"></span>&nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"text\" id=\"txtReply\" size=50>\r\n");
      out.write("\t\t<button id=\"btnInsert\">입력</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"tbl\"></div>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t{{#each list}}\r\n");
      out.write("\t\t<div class=\"divContent\">\r\n");
      out.write("\t\t\t<div class=\"replydate\">\r\n");
      out.write("\t\t\t\t{{replydate}}\r\n");
      out.write("\t\t\t\t[<b>{{replyer}}</b>]\r\n");
      out.write("\t\t\t\t<button rno={{rno}} style=\"{{printStyle replyer}}\">삭제</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"reply\">{{reply}}</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div id=\"pagination\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\tvar replyer=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tvar bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tvar page=1;\r\n");
      out.write("\t\r\n");
      out.write("\tHandlebars.registerHelper(\"printStyle\",function(writer){\r\n");
      out.write("\t\t   var src;\r\n");
      out.write("\t\t   if(replyer!=writer) src=\"display:none;\";\r\n");
      out.write("\t\t   return src;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tbl\").on(\"click\", \".replydate button\", function(){\r\n");
      out.write("\t\tvar rno=$(this).attr(\"rno\");\r\n");
      out.write("\t\tif(!confirm(rno + \" 댓글을 삭제?\")) return;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/reply/delete\",\r\n");
      out.write("\t\t\tdata:{\"rno\":rno},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"삭제완료!\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#txtReply\").keydown(function(key){\r\n");
      out.write("\t\tif(key.keyCode==13){\r\n");
      out.write("\t\t\t$(\"#btnInsert\").click();\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tvar reply=$(\"#txtReply\").val();\r\n");
      out.write("\t\tif(reply==\"\"){\r\n");
      out.write("\t\t\talert(\"댓글 내용을 입력하세요!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/reply/insert\",\r\n");
      out.write("\t\t\tdata:{\"bno\":bno,\"reply\":reply,\"replyer\":replyer},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"댓글입력!\");\r\n");
      out.write("\t\t\t\t$(\"#txtReply\").val(\"\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tgetList();\r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"/reply/list\",\r\n");
      out.write("\t\t\tdata:{\"bno\":bno, \"page\":page},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("                $(\"#tbl\").html(temp(data));\r\n");
      out.write("                $(\"#count\").html(data.count);\r\n");
      out.write("                \r\n");
      out.write("              \t//페이지 리스트 출력\r\n");
      out.write("                var str=\"\";\r\n");
      out.write("                if(data.pm.prev){\r\n");
      out.write("                    str += \"<a href='\" + (data.pm.startPage-1) + \"'>◀</a>\"\r\n");
      out.write("                }\r\n");
      out.write("                for(var i=data.pm.startPage; i<= data.pm.endPage; i++){\r\n");
      out.write("                    if(data.pm.cri.page == i){\r\n");
      out.write("                        str += \"[<a href='\" + i + \"' class='active'>\" + i + \"</a>]\";\r\n");
      out.write("                    }else{\r\n");
      out.write("                        str += \"[<a href='\" + i + \"'>\" + i + \"</a>]\";\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                if(data.pm.next){\r\n");
      out.write("                    str += \"<a href='\" + (data.pm.endPage+1)  +  \"'>▶</a>\"\r\n");
      out.write("                }\r\n");
      out.write("                $(\"#pagination\").html(str);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t    //페이지 번호를 클릭했을 경우\r\n");
      out.write("\t    $(\"#pagination\").on(\"click\", \"a\", function(event){\r\n");
      out.write("\t        event.preventDefault();\r\n");
      out.write("\t        page = $(this).attr(\"href\");\r\n");
      out.write("\t        getList();\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
