/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-06 06:25:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pro;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <title>상품등록</title>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("   <style>\r\n");
      out.write("   \t\tinput[type='file'] {visibility:hidden; height:0px;} \r\n");
      out.write("   \t\t#listFile img {width:150px;margin-left:20px; }\r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>[상품등록]</h1>\r\n");
      out.write("   <form name=\"frm\" action=\"insert\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <table border=1>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=100>상품코드</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"pcode\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=100>상품명</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"pname\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=100>상품가격</td>\r\n");
      out.write("            <td><input type=\"number\" name=\"price\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=100>대표이미지</td>\r\n");
      out.write("            <td width=400>\r\n");
      out.write("               <input type=\"file\" name=\"file\">\r\n");
      out.write("               <img id=\"image\" src=\"http://placehold.it/150x120\" width=150>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("         \t<td width=100>\r\n");
      out.write("         \t\t<input type=\"button\" value=\"상품이미지\" id=\"btnImage\">\r\n");
      out.write("         \t</td>\r\n");
      out.write("         \t<td width=400 height=150>\r\n");
      out.write("         \t\t<input type=\"file\" name=\"files\" accept=\"image/*\" multiple>\r\n");
      out.write("         \t\t<div id=\"listFile\"></div>\r\n");
      out.write("         \t</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <input type=\"submit\" value=\"저장\">\r\n");
      out.write("      <input type=\"reset\" value=\"취소\">\r\n");
      out.write("      <input type=\"button\" value=\"목록\" id=\"btnList\">\r\n");
      out.write("   </form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t//상품이미지 버튼을 눌렀을때\r\n");
      out.write("\t$(\"#btnImage\").on(\"click\", function(){\r\n");
      out.write("\t\t$(frm.files).click();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//여러 사진파일을 올릴때\r\n");
      out.write("\t $(frm.files).on(\"change\", function(){\r\n");
      out.write("\t      var files=$(frm.files)[0].files;\r\n");
      out.write("\t      var html=\"\";\r\n");
      out.write("\t      $.each(files, function(index, file){\r\n");
      out.write("\t    \t html += \"<img src='\" + URL.createObjectURL(file) + \"'>\"; \r\n");
      out.write("\t      });\r\n");
      out.write("\t      $(\"#listFile\").html(html);\r\n");
      out.write("\t   });\r\n");
      out.write("\t\r\n");
      out.write("\t//목록버튼\r\n");
      out.write("\t$(\"#btnList\").on(\"click\", function(){\r\n");
      out.write("\t\tlocation.href=\"list\";\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#image\").on(\"click\", function(){\r\n");
      out.write("\t\t$(frm.file).click();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("   $(frm.file).on(\"change\", function(){\r\n");
      out.write("      var file=$(frm.file)[0].files[0];\r\n");
      out.write("      $(\"#image\").attr(\"src\", URL.createObjectURL(file))\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
