/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-07-08 02:47:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>크롤링 결과</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[다음날씨]</h1>\r\n");
      out.write("\t<div id=\"daum\">\r\n");
      out.write("\t\t<span id=\"today\"></span>\r\n");
      out.write("\t\t<span id=\"weather\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>[네이버 거래상위]</h1>\r\n");
      out.write("\t<div id=\"naver\">\r\n");
      out.write("\t\t<span id=\"finance\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>[영화 상위]</h1>\r\n");
      out.write("\t<div id=\"movie\">\r\n");
      out.write("\t\t<span id=\"poster\"></span><br>\r\n");
      out.write("\t\t<span id=\"movieInfo\"></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("getWeather();\r\n");
      out.write("var weather=[];\r\n");
      out.write("function getWeather() {\r\n");
      out.write("$.ajax({\r\n");
      out.write("\ttype : \"get\",\r\n");
      out.write("\turl : \"/weather.json\",\r\n");
      out.write("\tdataType : \"json\",\r\n");
      out.write("\tsuccess : function(data) {\r\n");
      out.write("\t\t$(\"#today\").html(data.date);\r\n");
      out.write("\t\tvar i=0;\r\n");
      out.write("\t\t$(data.array).each(function(){\r\n");
      out.write("\t\t\tvar part=this.part;\r\n");
      out.write("\t\t\tvar ico=this.ico;\r\n");
      out.write("\t\t\tvar temper=this.temper;\r\n");
      out.write("\t\t\tvar wa=this.wa;\r\n");
      out.write("\t\t\t//console.log(part+ico+temper+wa); //콘솔창에 띄우는거\r\n");
      out.write("\t\t\tweather[i]=part+\" \"+ico+\" \"+temper+wa;\r\n");
      out.write("\t\t\ti++;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t i=0;\r\n");
      out.write("\t\t\tvar interval=setInterval(function(){\r\n");
      out.write("\t\t\t\t$(\"#weather\").html(weather[i]);\r\n");
      out.write("\t\t\t\tif(i<weather.length-1){\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ti=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},2000);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("getfinance();\r\n");
      out.write("var finance=[];\r\n");
      out.write("function getfinance() {\r\n");
      out.write("$.ajax({\r\n");
      out.write("\ttype : \"get\",\r\n");
      out.write("\turl : \"/finance.json\",\r\n");
      out.write("\tdataType : \"json\",\r\n");
      out.write("\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar i=0;\r\n");
      out.write("\t\t$(data.array).each(function(){\r\n");
      out.write("\t\t\tvar company=this.company;\r\n");
      out.write("\t\t\tvar no1=this.no1;\r\n");
      out.write("\t\t\tvar no2=this.no2;\r\n");
      out.write("\t\t\tvar no3=this.no3;\r\n");
      out.write("\t\t\tvar no4=this.no4;\r\n");
      out.write("\t\t\t//console.log(part+ico+temper+wa); //콘솔창에 띄우는거\r\n");
      out.write("\t\t\tfinance[i]=company+\" \"+no1+\" \"+no2+\" \"+no3+\" \"+no4\r\n");
      out.write("\t\t\ti++;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t i=0;\r\n");
      out.write("\t\t\tvar interval=setInterval(function(){\r\n");
      out.write("\t\t\t\t$(\"#finance\").html(finance[i]);\r\n");
      out.write("\t\t\t\tif(i<finance.length-1){\r\n");
      out.write("\t\t\t\t\ti++;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ti=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},2000);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("getmovie();\r\n");
      out.write("var mov=[];\r\n");
      out.write("var pos=[];\r\n");
      out.write("\r\n");
      out.write("function getmovie(){\r\n");
      out.write("   $.ajax({\r\n");
      out.write("      type : \"get\",\r\n");
      out.write("      url : \"/movie.json\",\r\n");
      out.write("      dataType : \"json\",\r\n");
      out.write("      success : function(data) {\r\n");
      out.write("         var i=0;\r\n");
      out.write("         $(data.array).each(function(){\r\n");
      out.write("            var rank=this.rank;\r\n");
      out.write("            var title=this.title;\r\n");
      out.write("            var date=this.date;\r\n");
      out.write("            var image=this.image;\r\n");
      out.write("            mov[i]=rank + \"\" + title +  \"\" + date\r\n");
      out.write("            pos[i]=image\r\n");
      out.write("            i++;\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         i=0\r\n");
      out.write("         var interval=setInterval(function(){\r\n");
      out.write("            $(\"#movieInfo\").html(mov[i]);\r\n");
      out.write("            $(\"#poster\").html(\"<img src=\"+pos[i]+\">\");\r\n");
      out.write("            if(i<mov.length-1){\r\n");
      out.write("               i++;\r\n");
      out.write("            }else{\r\n");
      out.write("               i=0;\r\n");
      out.write("            }\r\n");
      out.write("         },2000);\r\n");
      out.write("      }\r\n");
      out.write("   })   \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
